fix decimal benchmarks file layout
Benchmark files moved to math subfolder, which becomes the only target
(as of now) of the benchmarks.
In previous layout each benchmark file was a separate target (autodetected by cargo),
which led to following errors, when building without `math` target:

$ cargo bench -p radix-engine-interface
"error[E0432]: unresolved import
 --> radix-engine-interface/benches/precise_decimal.rs:7:12
  |
7 | use crate::macros::QUICK;
  |            ^^^^^^ could not find  in the crate root
"